-- require("plugin_config/nvim_tree")
require("plugin_config/nvim_autopairs")
require("plugin_config/nvim_comment")
require("plugin_config/nvim_treesitter")
require("plugin_config/gitsigns")
require("plugin_config/formatter")
require("plugin_config/cmp")
require("plugin_config/lsp")
require("plugin_config/luasnip")
require("plugin_config/fzf")
